### ISSUE TITLE
Unrelated: Questions...

### ISSUE THREAD

**Issue by MythreyaK** [TranslucentTB/Tools#1]
Hello, this is unrelated to the tools, but I was hoping I could learn some stuff. 

I tried using API Monitor tools to monitor Calculator.exe (the new Store app, with Acrylic blur) and dwm.exe itself, but couldn't find calls to `SetWindowCompositionAttribute`. There were calls to `GetWindowCompositionAttribute`, but didn't reveal any useful information. I was wondering, where and how did one stumble upon this? 

I tried to make an app that uses `ACCENT_ENABLE_ACRYLICBLURBEHIND`, but this results in resizing and moving the window to be extremely laggy and broken. Why this? I'm just playing around, hoping to keep the acrylic blur even after the app has lost focus. 

Thanks!

**Comment by sylveon** [comment]
> I tried using API Monitor tools to monitor Calculator.exe (the new Store app, with Acrylic blur) and dwm.exe itself, but couldn't find calls to `SetWindowCompositionAttribute`. There were calls to `GetWindowCompositionAttribute`, but didn't reveal any useful information. I was wondering, where and how did one stumble upon this?

The calculator uses UWP's [AcrylicBrush](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.acrylicbrush), monitoring `SetWindowCompositionAttribute` is not likely to help: https://github.com/microsoft/calculator/blob/1a9edff26b3fb8f7a1dcdf13e860da7794d4cf13/src/Calculator/App.xaml#L60

You can stumble upon usage of `SetWindowCompositionAttribute` in the taskbar. It's not a UWP app so uses this undocumented API to get the acrylic effect.

> I tried to make an app that uses `ACCENT_ENABLE_ACRYLICBLURBEHIND`, but this results in resizing and moving the window to be extremely laggy and broken. Why this? I'm just playing around, hoping to keep the acrylic blur even after the app has lost focus.

This is a bug Windows 1903, updating to 1909 should fix it.

**Comment by MythreyaK** [comment]
Wow this means that UWP doesn't use `SetWindowCompositionAttribute` at all! I was under the impression that this was the case! So, under the hood, all the fancy effects from UWP are through other APIs then... 

> You can stumble upon usage of SetWindowCompositionAttribute in the taskbar. It's not a UWP app so uses this undocumented API to get the acrylic effect.

That makes sense! That's the reason my app _and_ the taskbar become transparent when switching desktops (with the trackpad gesture).

> This is a bug Windows 1903, updating to 1909 should fix it.

The command being a hidden one, I must say finding that it's a bug is pretty cool!

How were these tools used for the development of TranslucentTB, since you already knew the hidden API (Looks and works amazing btw)?

Thank you for your prompt reply!

**Comment by sylveon** [comment]
Actually the bug manifested in Microsoft's emoji picker (`Win+.` or `Win+;`), which is also Win32 and uses `SetWindowCompositionAttribute`. If the bug didn't manifest in that it would probably never get fixed because undocumented APIs need no support/bug fixing.

Most of TranslucentTB's logic is not `SetWindowCompositionAttribute`. A call to this undocumented API is just the end result of hundreds of documented API calls to figure out the layout of windows on the desktop. I did dig a big into reverse engineering to figure out a couple other things, but they're non essential (mostly the event hook to use to detect when the user enter/leaves Aero Peek and the message to send to the taskbar window so that it returns to its normal style).

**Comment by MythreyaK** [comment]
Hmmm I am on 1903 and didn't notice it the emoji picker. But it sure is there in the start menu, notification center and the taskbar! Nice to know that it's fixed in the next release!

> … big into reverse engineering  ...

That sounds really fun!

Thank you very much for your responses!

**Comment by sylveon** [comment]
Woops, typo for bit

**Comment by MythreyaK** [comment]
I just updated to 1909, sadly the bug is still there :/
Update: Just make a clean install (due to reasons), the issue persists!

**Comment by sylveon** [comment]
My bad, this is probably fixed in 20H1 then.

**Comment by MythreyaK** [comment]
You're right! Just checked with the release notes. Thank you!
